#  NUMPY
    A linear algebra based library
    Most machine learning packages internally uses numpy 


# Installation

### From python:
    pip install numpy
    
###  From Anaconda:
    conda install numpy

In [1]:
import numpy as np

## Numpy Arrays

In [2]:
# From python list
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_arr = np.array([1,2,3])

In [6]:
my_arr

array([1, 2, 3])

In [7]:
# Import direct function from package
from numpy import array as a1
a1([1,2,3])

array([1, 2, 3])

## Index elements from an Array

In [8]:
arr = np.arange(10)

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[3]

3

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [13]:
arr[5:]

array([5, 6, 7, 8, 9])

In [14]:
# Broadcast values
arr[0:5] = -1
arr

array([-1, -1, -1, -1, -1,  5,  6,  7,  8,  9])

# How to copy from one array to another

In [15]:
arr = np.arange(10)

In [16]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
slice_of_arr  = arr[0:5]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [19]:
slice_of_arr[:] = 100

In [20]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [22]:
arr_copy = arr.copy()

In [23]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [24]:
arr_copy[:] = -1

In [25]:
arr_copy

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [26]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

## 2-D Arrays or Matrix

In [27]:
list_lists = [[1,2,3],[4,5,6],[7,8,9]]

In [28]:
list_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [29]:
my_matrix = np.array(list_lists)

In [30]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing and selecting 2-D Arrays 

In [31]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
my_matrix[0]

array([1, 2, 3])

In [33]:
my_matrix[0][0]

1

In [34]:
my_matrix[0,0]

1

In [35]:
my_matrix[0:2,1:]

array([[2, 3],
       [5, 6]])

In [36]:
list_lists = [[1,2,3,4],[4,5,6,7],[7,8,9,10]]
my_matrix = np.array(list_lists)

In [37]:
my_matrix

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [39]:
my_matrix[1:, 1:3]

array([[5, 6],
       [8, 9]])

## Built in methods

In [40]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [42]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [44]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [45]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [46]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [47]:
np.linspace(0,20,5)

array([  0.,   5.,  10.,  15.,  20.])

In [48]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [49]:
# IDENTITY MATRIX
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [50]:
# RANDOM

# rand -- is used to populate random samples from a uniform distribution over [0,1)
np.random.rand(10)

array([ 0.92209605,  0.54686148,  0.30991505,  0.19883108,  0.05469955,
        0.42271994,  0.28814764,  0.91599064,  0.75592747,  0.89528775])

In [51]:
np.random.rand(5,5)

array([[ 0.68741094,  0.01287971,  0.12284836,  0.45323281,  0.4115114 ],
       [ 0.60194034,  0.13481005,  0.86182086,  0.02519551,  0.06135231],
       [ 0.64333697,  0.51924613,  0.2410446 ,  0.24503857,  0.57485523],
       [ 0.29809447,  0.56966088,  0.98241058,  0.11626337,  0.05105307],
       [ 0.65548755,  0.0140278 ,  0.18597376,  0.21171585,  0.53364057]])

In [52]:
# randn -- is used to populate randome samples from standard normal distribution
np.random.randn(10)

array([ 0.19386864, -0.33554988, -0.22272471,  1.48201668,  1.20043472,
       -0.32596228,  0.47230163,  0.45817564, -2.19392006, -0.07085133])

In [53]:
np.random.randn(5,5)

array([[-0.18198349,  2.07158989, -0.94976487, -0.2995956 , -1.1159815 ],
       [ 0.74721974,  0.72625834,  1.28254893,  1.09514917,  0.14339109],
       [ 1.7259056 , -1.33309597,  1.30630368,  1.85973119, -0.38086012],
       [ 1.89685187,  1.98471422, -0.52804402, -0.31067199,  0.70025286],
       [ 1.96855656,  0.91859776, -0.55386422,  0.53118388,  0.39772299]])

In [54]:
# randint -- random integers between start and end values
np.random.randint(0,10)

5

In [55]:
np.random.randint(0,100, 10)

array([58, 40, 70, 68, 77, 79, 45, 14,  2, 62])

In [56]:
# RESHAPE
arr = np.random.randint(0,100, 25)

In [57]:
arr

array([13, 50, 76, 34, 20, 56, 67, 29, 95, 69, 46, 38, 70, 94, 56, 70, 29,
        7, 16, 29, 30, 53, 34, 77,  0])

In [58]:
arr.reshape(5,5)

array([[13, 50, 76, 34, 20],
       [56, 67, 29, 95, 69],
       [46, 38, 70, 94, 56],
       [70, 29,  7, 16, 29],
       [30, 53, 34, 77,  0]])

In [59]:
arr

array([13, 50, 76, 34, 20, 56, 67, 29, 95, 69, 46, 38, 70, 94, 56, 70, 29,
        7, 16, 29, 30, 53, 34, 77,  0])

In [60]:
len(arr)

25

In [61]:
arr.max()

95

In [62]:
arr.min()

0

In [63]:
# to return index location of max value
arr.argmax()

8

In [64]:
# to return index location of min value
arr.argmin()

24

In [65]:
arr

array([13, 50, 76, 34, 20, 56, 67, 29, 95, 69, 46, 38, 70, 94, 56, 70, 29,
        7, 16, 29, 30, 53, 34, 77,  0])

In [66]:
# reshape 
arr.reshape(1,25)


array([[13, 50, 76, 34, 20, 56, 67, 29, 95, 69, 46, 38, 70, 94, 56, 70, 29,
         7, 16, 29, 30, 53, 34, 77,  0]])

In [67]:
arr.reshape(1,25).shape

(1, 25)

In [68]:
arr.reshape(5,5)

array([[13, 50, 76, 34, 20],
       [56, 67, 29, 95, 69],
       [46, 38, 70, 94, 56],
       [70, 29,  7, 16, 29],
       [30, 53, 34, 77,  0]])

In [69]:
arr.reshape(5,5).shape

(5, 5)

In [70]:
# to find the data type of an array
arr.dtype

dtype('int32')