## DataFrames - main tool to handle data

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn

In [3]:
np.random.seed(101)

In [4]:
randn(5,5)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575,  0.65111795],
       [-0.31931804, -0.84807698,  0.60596535, -2.01816824,  0.74012206],
       [ 0.52881349, -0.58900053,  0.18869531, -0.75887206, -0.93323722],
       [ 0.95505651,  0.19079432,  1.97875732,  2.60596728,  0.68350889],
       [ 0.30266545,  1.69372293, -1.70608593, -1.15911942, -0.13484072]])

In [5]:
my_matrix = np.random.rand(5,5)

In [6]:
my_matrix

array([[ 0.86509982,  0.83027771,  0.53816145,  0.92246937,  0.09714648],
       [ 0.10284749,  0.7015073 ,  0.89047987,  0.1595603 ,  0.27557254],
       [ 0.67249153,  0.16430312,  0.70137114,  0.48763522,  0.68067777],
       [ 0.52154819,  0.04339669,  0.2239366 ,  0.57520509,  0.12043366],
       [ 0.50011671,  0.13800957,  0.0528084 ,  0.17827692,  0.44236813]])

In [7]:
-1 * my_matrix

array([[-0.86509982, -0.83027771, -0.53816145, -0.92246937, -0.09714648],
       [-0.10284749, -0.7015073 , -0.89047987, -0.1595603 , -0.27557254],
       [-0.67249153, -0.16430312, -0.70137114, -0.48763522, -0.68067777],
       [-0.52154819, -0.04339669, -0.2239366 , -0.57520509, -0.12043366],
       [-0.50011671, -0.13800957, -0.0528084 , -0.17827692, -0.44236813]])

In [8]:
df = pd.DataFrame(data=randn(5,5), index=['A','B','C','D','E'],columns=['meter1','meter2','meter3','meter4','meter5'] )

In [9]:
df

meter1    meter2    meter3    meter4    meter5
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544
B  1.131029  0.498600  1.179022  1.322684  1.852155
C -0.892172  0.616861 -1.121822  1.652070  0.196925
D  0.103214 -0.147370  1.131284  1.085839  0.449486
E -0.002963 -0.648177 -0.956150  1.610461  1.319618

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df['meter1']

A    0.390528
B    1.131029
C   -0.892172
D    0.103214
E   -0.002963
Name: meter1, dtype: float64

In [12]:
type(df['meter1'])

pandas.core.series.Series

In [13]:
# Not recommended
df.meter1

A    0.390528
B    1.131029
C   -0.892172
D    0.103214
E   -0.002963
Name: meter1, dtype: float64

In [14]:
df['meter1']

A    0.390528
B    1.131029
C   -0.892172
D    0.103214
E   -0.002963
Name: meter1, dtype: float64

In [15]:
df[['meter1','meter2']]

meter1    meter2
A  0.390528 -2.711192
B  1.131029  0.498600
C -0.892172  0.616861
D  0.103214 -0.147370
E -0.002963 -0.648177

In [16]:
# creating a new column
df['east'] = df['meter1']+df['meter5']

In [17]:
df

meter1    meter2    meter3    meter4    meter5      east
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544  1.499072
B  1.131029  0.498600  1.179022  1.322684  1.852155  2.983183
C -0.892172  0.616861 -1.121822  1.652070  0.196925 -0.695247
D  0.103214 -0.147370  1.131284  1.085839  0.449486  0.552700
E -0.002963 -0.648177 -0.956150  1.610461  1.319618  1.316655

In [18]:
# drop a column
df.drop('east', axis = 1)

meter1    meter2    meter3    meter4    meter5
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544
B  1.131029  0.498600  1.179022  1.322684  1.852155
C -0.892172  0.616861 -1.121822  1.652070  0.196925
D  0.103214 -0.147370  1.131284  1.085839  0.449486
E -0.002963 -0.648177 -0.956150  1.610461  1.319618

In [19]:
df.drop('east', axis = 1, inplace=True)

In [20]:
df

meter1    meter2    meter3    meter4    meter5
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544
B  1.131029  0.498600  1.179022  1.322684  1.852155
C -0.892172  0.616861 -1.121822  1.652070  0.196925
D  0.103214 -0.147370  1.131284  1.085839  0.449486
E -0.002963 -0.648177 -0.956150  1.610461  1.319618

In [21]:
# drop an index
df.drop('A', axis = 0)

meter1    meter2    meter3    meter4    meter5
B  1.131029  0.498600  1.179022  1.322684  1.852155
C -0.892172  0.616861 -1.121822  1.652070  0.196925
D  0.103214 -0.147370  1.131284  1.085839  0.449486
E -0.002963 -0.648177 -0.956150  1.610461  1.319618

In [22]:
df

meter1    meter2    meter3    meter4    meter5
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544
B  1.131029  0.498600  1.179022  1.322684  1.852155
C -0.892172  0.616861 -1.121822  1.652070  0.196925
D  0.103214 -0.147370  1.131284  1.085839  0.449486
E -0.002963 -0.648177 -0.956150  1.610461  1.319618

In [23]:
df['east'] = df['meter1']+df['meter5']

In [24]:
df

meter1    meter2    meter3    meter4    meter5      east
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544  1.499072
B  1.131029  0.498600  1.179022  1.322684  1.852155  2.983183
C -0.892172  0.616861 -1.121822  1.652070  0.196925 -0.695247
D  0.103214 -0.147370  1.131284  1.085839  0.449486  0.552700
E -0.002963 -0.648177 -0.956150  1.610461  1.319618  1.316655

In [25]:
df = df.drop('east', axis = 1)

In [26]:
df

meter1    meter2    meter3    meter4    meter5
A  0.390528 -2.711192 -1.522410 -1.416207  1.108544
B  1.131029  0.498600  1.179022  1.322684  1.852155
C -0.892172  0.616861 -1.121822  1.652070  0.196925
D  0.103214 -0.147370  1.131284  1.085839  0.449486
E -0.002963 -0.648177 -0.956150  1.610461  1.319618

In [27]:
df = df.drop('meter5', axis = 1)
df

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
C -0.892172  0.616861 -1.121822  1.652070
D  0.103214 -0.147370  1.131284  1.085839
E -0.002963 -0.648177 -0.956150  1.610461

In [28]:
df.shape

(5, 4)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
meter1    5 non-null float64
meter2    5 non-null float64
meter3    5 non-null float64
meter4    5 non-null float64
dtypes: float64(4)
memory usage: 360.0+ bytes


In [30]:
df.describe()

meter1    meter2    meter3    meter4
count  5.000000  5.000000  5.000000  5.000000
mean   0.145927 -0.478256 -0.258015  0.850970
std    0.730051  1.348878  1.306472  1.288057
min   -0.892172 -2.711192 -1.522410 -1.416207
25%   -0.002963 -0.648177 -1.121822  1.085839
50%    0.103214 -0.147370 -0.956150  1.322684
75%    0.390528  0.498600  1.131284  1.610461
max    1.131029  0.616861  1.179022  1.652070

In [31]:
#Selecting columns
df[['meter1','meter2','meter3']]

meter1    meter2    meter3
A  0.390528 -2.711192 -1.522410
B  1.131029  0.498600  1.179022
C -0.892172  0.616861 -1.121822
D  0.103214 -0.147370  1.131284
E -0.002963 -0.648177 -0.956150

In [32]:
# Selecting rows -- two ways to select rows
df.loc['A']

meter1    0.390528
meter2   -2.711192
meter3   -1.522410
meter4   -1.416207
Name: A, dtype: float64

In [33]:
# Even though index has different names, we can access by 0,1,2... using 'iloc'
df.iloc[0]

meter1    0.390528
meter2   -2.711192
meter3   -1.522410
meter4   -1.416207
Name: A, dtype: float64

In [34]:
df.iloc[1]

meter1    1.131029
meter2    0.498600
meter3    1.179022
meter4    1.322684
Name: B, dtype: float64

In [35]:
# Selecting subsets of rows and columns
df.loc['B','meter1']

1.1310285847642976

In [36]:
df.loc[['A','B'], ['meter1','meter2'] ]

meter1    meter2
A  0.390528 -2.711192
B  1.131029  0.498600

### Conditional Selection

In [37]:
df

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
C -0.892172  0.616861 -1.121822  1.652070
D  0.103214 -0.147370  1.131284  1.085839
E -0.002963 -0.648177 -0.956150  1.610461

In [38]:
df>0

meter1  meter2  meter3  meter4
A    True   False   False   False
B    True    True    True    True
C   False    True   False    True
D    True   False    True    True
E   False   False   False    True

In [39]:
df[df>0]

meter1    meter2    meter3    meter4
A  0.390528       NaN       NaN       NaN
B  1.131029  0.498600  1.179022  1.322684
C       NaN  0.616861       NaN  1.652070
D  0.103214       NaN  1.131284  1.085839
E       NaN       NaN       NaN  1.610461

In [40]:
df['meter1']>0

A     True
B     True
C    False
D     True
E    False
Name: meter1, dtype: bool

In [41]:
df[df['meter1']>0]

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
D  0.103214 -0.147370  1.131284  1.085839

In [42]:
meter1_positive = df[df['meter1']>0]

In [43]:
meter1_positive

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
D  0.103214 -0.147370  1.131284  1.085839

In [44]:
meter1_positive[['meter3','meter4']]

meter3    meter4
A -1.522410 -1.416207
B  1.179022  1.322684
D  1.131284  1.085839

In [45]:
df[df['meter1']>0][['meter3','meter4']]

meter3    meter4
A -1.522410 -1.416207
B  1.179022  1.322684
D  1.131284  1.085839

In [46]:
df

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
C -0.892172  0.616861 -1.121822  1.652070
D  0.103214 -0.147370  1.131284  1.085839
E -0.002963 -0.648177 -0.956150  1.610461

In [47]:
# Multiple conditions
df[(df['meter1']>0) & (df['meter2']>-1)]

meter1   meter2    meter3    meter4
B  1.131029  0.49860  1.179022  1.322684
D  0.103214 -0.14737  1.131284  1.085839

In [48]:
df[(df['meter1']>0) | (df['meter2']>-1)]

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
C -0.892172  0.616861 -1.121822  1.652070
D  0.103214 -0.147370  1.131284  1.085839
E -0.002963 -0.648177 -0.956150  1.610461

## DataFrame Index Edits

In [49]:
df

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
C -0.892172  0.616861 -1.121822  1.652070
D  0.103214 -0.147370  1.131284  1.085839
E -0.002963 -0.648177 -0.956150  1.610461

In [50]:
df.reset_index()

index    meter1    meter2    meter3    meter4
0     A  0.390528 -2.711192 -1.522410 -1.416207
1     B  1.131029  0.498600  1.179022  1.322684
2     C -0.892172  0.616861 -1.121822  1.652070
3     D  0.103214 -0.147370  1.131284  1.085839
4     E -0.002963 -0.648177 -0.956150  1.610461

In [51]:
df

meter1    meter2    meter3    meter4
A  0.390528 -2.711192 -1.522410 -1.416207
B  1.131029  0.498600  1.179022  1.322684
C -0.892172  0.616861 -1.121822  1.652070
D  0.103214 -0.147370  1.131284  1.085839
E -0.002963 -0.648177 -0.956150  1.610461

In [52]:
df.reset_index(inplace=True)

In [53]:
df

index    meter1    meter2    meter3    meter4
0     A  0.390528 -2.711192 -1.522410 -1.416207
1     B  1.131029  0.498600  1.179022  1.322684
2     C -0.892172  0.616861 -1.121822  1.652070
3     D  0.103214 -0.147370  1.131284  1.085839
4     E -0.002963 -0.648177 -0.956150  1.610461

In [54]:
newInd = ['aa','bb','cc','dd','ee']

In [55]:
df['newInd'] = newInd

In [56]:
df

index    meter1    meter2    meter3    meter4 newInd
0     A  0.390528 -2.711192 -1.522410 -1.416207     aa
1     B  1.131029  0.498600  1.179022  1.322684     bb
2     C -0.892172  0.616861 -1.121822  1.652070     cc
3     D  0.103214 -0.147370  1.131284  1.085839     dd
4     E -0.002963 -0.648177 -0.956150  1.610461     ee

In [57]:
df.set_index('newInd', inplace=True)

In [58]:
df

index    meter1    meter2    meter3    meter4
newInd                                              
aa         A  0.390528 -2.711192 -1.522410 -1.416207
bb         B  1.131029  0.498600  1.179022  1.322684
cc         C -0.892172  0.616861 -1.121822  1.652070
dd         D  0.103214 -0.147370  1.131284  1.085839
ee         E -0.002963 -0.648177 -0.956150  1.610461